frequency <- c(0.6, 0.3, 0.4, 0.4, 0.2, 0.6, 0.3, 0.4, 0.9, 0.2)
bloodp <- c(103, 87, 32, 42, 59, 109, 78, 205, 135, 176)
first <- c(1, 1, 1, 1, 0, 0, 0, 0, NA, 1)
second <- c(0, 0, 1, 1, 0, 0, 1, 1, 1, 1)
finaldecision <- c(0, 1, 0, 1, 0, 1, 0, 1, 1, 1)
boxplot(frequency, ylab='Frequency', main='Visit Frequency in last 12 Months')
boxplot(bloodp, ylab='Blood Pressure', main='Blood Pressure Measurement')
boxplot(first, second, finaldecision, names=c('First\nDoctor', 'Second\nDoctor', 'Final\nAssessment'), ylab='Assessment', main='Doctor Assessments', digits.d=2, cex.axis=.75)
hist(frequency, xlab = 'Patient Frequency', main='Visit Frequency in last 12 Months')
hist(bloodp, xlab = 'Blood Pressure', main='Blood Pressure Measurement')
hist(first, xlab = 'Assessment', main = 'First Doctors Assessment')
hist(second, xlab = 'Assessment', main = 'Second Doctors Assessment')
hist(finaldecision, xlab = 'Assessment', main = 'Final Assessment')